<?php //Do not edit this file by hand, it will be overwritten by the configuration utility. 
$SALARY_ACCOUNTING_USERS['5'] = '1';
$SALARY_ACCOUNTING_USERS['2'] = '1';
$NEW_SALARY_NOTIFY = 1;
$PERCENT_DONE = 75;
?>
